package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/celtcoste/go-graphql-api-template/internal/graph/generated"
	"github.com/celtcoste/go-graphql-api-template/internal/graph/model"
)

// OfferNumber is the resolver for the offerNumber field.
func (r *userResolver) OfferNumber(ctx context.Context, obj *model.User) (int, error) {
	panic(fmt.Errorf("not implemented: OfferNumber - offerNumber"))
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
